/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v7.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f030027;
        public static final int coordinatorLayoutStyle = 0x7f0300a4;
        public static final int fastScrollEnabled = 0x7f0300d0;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f0300d1;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f0300d2;
        public static final int fastScrollVerticalThumbDrawable = 0x7f0300d3;
        public static final int fastScrollVerticalTrackDrawable = 0x7f0300d4;
        public static final int font = 0x7f0300d7;
        public static final int fontProviderAuthority = 0x7f0300d9;
        public static final int fontProviderCerts = 0x7f0300da;
        public static final int fontProviderFetchStrategy = 0x7f0300db;
        public static final int fontProviderFetchTimeout = 0x7f0300dc;
        public static final int fontProviderPackage = 0x7f0300dd;
        public static final int fontProviderQuery = 0x7f0300de;
        public static final int fontStyle = 0x7f0300df;
        public static final int fontVariationSettings = 0x7f0300e0;
        public static final int fontWeight = 0x7f0300e1;
        public static final int keylines = 0x7f03010d;
        public static final int layoutManager = 0x7f030111;
        public static final int layout_anchor = 0x7f030112;
        public static final int layout_anchorGravity = 0x7f030113;
        public static final int layout_behavior = 0x7f030114;
        public static final int layout_dodgeInsetEdges = 0x7f030140;
        public static final int layout_insetEdge = 0x7f030149;
        public static final int layout_keyline = 0x7f03014a;
        public static final int reverseLayout = 0x7f030185;
        public static final int spanCount = 0x7f03019a;
        public static final int stackFromEnd = 0x7f0301a0;
        public static final int statusBarBackground = 0x7f0301a6;
        public static final int ttcIndex = 0x7f030208;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f05006c;
        public static final int notification_icon_bg_color = 0x7f05006d;
        public static final int ripple_material_light = 0x7f050077;
        public static final int secondary_text_default_material_light = 0x7f050079;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060050;
        public static final int compat_button_inset_vertical_material = 0x7f060051;
        public static final int compat_button_padding_horizontal_material = 0x7f060052;
        public static final int compat_button_padding_vertical_material = 0x7f060053;
        public static final int compat_control_corner_material = 0x7f060054;
        public static final int compat_notification_large_icon_max_height = 0x7f060055;
        public static final int compat_notification_large_icon_max_width = 0x7f060056;
        public static final int fastscroll_default_thickness = 0x7f060085;
        public static final int fastscroll_margin = 0x7f060086;
        public static final int fastscroll_minimum_range = 0x7f060087;
        public static final int item_touch_helper_max_drag_scroll_per_frame = 0x7f06008f;
        public static final int item_touch_helper_swipe_escape_max_velocity = 0x7f060090;
        public static final int item_touch_helper_swipe_escape_velocity = 0x7f060091;
        public static final int notification_action_icon_size = 0x7f0600c2;
        public static final int notification_action_text_size = 0x7f0600c3;
        public static final int notification_big_circle_margin = 0x7f0600c4;
        public static final int notification_content_margin_start = 0x7f0600c5;
        public static final int notification_large_icon_height = 0x7f0600c6;
        public static final int notification_large_icon_width = 0x7f0600c7;
        public static final int notification_main_column_padding_top = 0x7f0600c8;
        public static final int notification_media_narrow_margin = 0x7f0600c9;
        public static final int notification_right_icon_size = 0x7f0600ca;
        public static final int notification_right_side_padding_top = 0x7f0600cb;
        public static final int notification_small_icon_background_padding = 0x7f0600cc;
        public static final int notification_small_icon_size_as_large = 0x7f0600cd;
        public static final int notification_subtext_size = 0x7f0600ce;
        public static final int notification_top_pad = 0x7f0600cf;
        public static final int notification_top_pad_large_text = 0x7f0600d0;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f070072;
        public static final int notification_bg = 0x7f070073;
        public static final int no